# Définir cette configuration Compose afin de lancer l'application
# Grilli en production.
version: '3.8'

services:
  php:
    build: .
    volumes:
      - website:/var/www/html

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .docker/nginx/grilli.com.conf:/etc/nginx/conf.d/default.conf
      - website:/var/www/html
    links: 
      - php

volumes:
  website: