# Définir cette configuration Compose afin de lancer l'application
# Grilli en production.
version: '3'

services:
  php-fpm:
    build:
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    networks:
      - app-network
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    networks:
      - app-network
networks:
  app-network:
    driver: bridge