version: '3'
services:
  server:
    build:
      context: ./server
    ports:
      - ${PORTS_SERVER}
  client:
    build:
      context: ./client
    ports:
      - ${PORTS_CLIENT}
    
    depends_on: 
      - server